import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useEffect,
	useReducer,
	useState } from "react"
import "../styles/UnderConstruction.module.css"

const UnderConstruction: NextPage = () => {
	const topColors = ["red", "orange", "amber", "yellow"]
	const bottomColors = ["teal", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose"]

	let [topColor, setTopColor] = useReducer((p: number, c: number) => c % topColors.length, 0)
	let [bottomColor, setBottomColor] = useReducer((p: number, c: number) => c % bottomColors.length, 0)

	useEffect(() => {
		let interval = setInterval(() => {
			setTopColor(topColor + 1)
			setBottomColor(bottomColor + 1)
		}, 5000)
		
		return () => clearInterval(interval)
	});

	return (
		<>
			<Head>
				<title>PACS LLC</title>
				<meta name="description" content="Generated by create next app" />
				<link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={[
				"grid",
				"h-full",
				"place-items-center",
				"main",
				"bg-gradient-to-b",
				`from-yellow-400`,
				`to-fuchsia-800`,
				"font-[Ubuntu]"
			].join(" ")}>
				<div className="flex flex-col items-center justify-center h-full">
					<Image src="/Pacs.png" alt="logo" width={220} height={220} />
					<h1 className="mt-[-50px] mb-5 text-4xl">&lt; UNDER CONSTRUCTION /&gt;</h1>
					<p><a href="tel:+19177500292">(917) 750-0292</a></p>
					<p><a href="mailto:info@pacsllc.net">info@pacsllc.net</a></p>
				</div>
			</main>
		</>
	)
}

export default UnderConstruction
